Adds optional serde support to datafusion-proto
apache/arrow-datafusion pull request #2892
Opened 2022-07-13 03:11 UTC by tustvold

# Which issue does this PR close?

Closes #2889

 # Rationale for this change

This provides a way to serialize the datafusion-proto messages to any serde serializer, e.g. JSON, based on the protobuf [JSON specification](https://developers.google.com/protocol-buffers/docs/proto3#json). 

# What changes are included in this PR?

Uses pbjson to auto-generate the serde implementations for the protobuf messages. Full disclosure: I am the primary author and maintainer of this crate.

# Are there any user-facing changes?

No

2022-07-13 03:12 UTC, tustvold commented on datafusion/proto/src/lib.rs
> +    fn roundtrip_expr_test<T, E>(initial_struct: T, ctx: SessionContext)
Drive by refactor to eliminate an unnecessary macro

2022-07-13 17:09 UTC, avantgardnerio commented on datafusion/proto/src/lib.rs
> +        let round_trip: Expr = parse_expr(&proto, &ctx).unwrap();
Oh, I was running my tests without the "serde" feature :facepalm:

2022-07-13 18:36 UTC, avantgardnerio commented on datafusion/proto/src/lib.rs
> +        let round_trip: Expr = parse_expr(&proto, &ctx).unwrap();
Okay, I got all that sorted, and was able to do what I was trying to use this PR for: https://github.com/tustvold/arrow-datafusion/pull/63

I was hoping (naively) to see something like:

```
{Projection: { field: "#employee_csv.id",
  Filter: {expr: {left: "#employee_csv.state", op: "IN", right: {
    Subquery: {
      TableScan: {name: "employee_csv", projection=["state"]},
    TableScan: {name: "employee_csv" projection=["id", "state"]
}}
```

Unfortunately (though serializable and deserializable) the result is not as human readable as I hoped, and probably not something I'd want to check into a test assertion: https://gist.github.com/avantgardnerio/35a04950ca768fdfe6579aea08126b74

2022-07-13 19:05 UTC, avantgardnerio commented on datafusion/proto/src/lib.rs
> +        let round_trip: Expr = parse_expr(&proto, &ctx).unwrap();
Running that raw JSON through [this formatter](https://github.com/lydell/json-stringify-pretty-compact) produces some encouraging output:

```
{
  "projection": {
    "input": {
      "sort": {
        "input": {
          "projection": {
            "input": {
              "listingScan": {
                "tableName": "alltypes_plain",
                "paths": ["file:///home/bgardner/workspace/arrow-datafusion/parquet-testing/data/alltypes_plain.parquet"],
                "fileExtension": ".parquet",
                "schema": {
                  "columns": [
                    {"name": "id", "arrowType": {"INT32": {}}, "nullable": true},
                    {"name": "bool_col", "arrowType": {"BOOL": {}}, "nullable": true},
                    {"name": "tinyint_col", "arrowType": {"INT32": {}}, "nullable": true},
                    {"name": "smallint_col", "arrowType": {"INT32": {}}, "nullable": true},
                    {"name": "int_col", "arrowType": {"INT32": {}}, "nullable": true},
                    {"name": "bigint_col", "arrowType": {"INT64": {}}, "nullable": true},
                    {"name": "float_col", "arrowType": {"FLOAT32": {}}, "nullable": true},
                    {"name": "double_col", "arrowType": {"FLOAT64": {}}, "nullable": true},
                    {"name": "date_string_col", "arrowType": {"BINARY": {}}, "nullable": true},
                    {"name": "string_col", "arrowType": {"BINARY": {}}, "nullable": true},
                    {"name": "timestamp_col", "arrowType": {"TIMESTAMP": {"timeUnit": "Nanosecond"}}, "nullable": true}
                  ]
                },
                "collectStat": true,
                "targetPartitions": 16,
                "parquet": {"enablePruning": true}
              }
            },
            "expr": [
              {"column": {"name": "id", "relation": {"relation": "alltypes_plain"}}},
              {"column": {"name": "int_col", "relation": {"relation": "alltypes_plain"}}},
              {"column": {"name": "double_col", "relation": {"relation": "alltypes_plain"}}}
            ]
          }
        },
        "expr": [
          {"sort": {"expr": {"column": {"name": "int_col", "relation": {"relation": "alltypes_plain"}}}, "asc": true}},
          {"sort": {"expr": {"column": {"name": "double_col", "relation": {"relation": "alltypes_plain"}}}, "asc": true}}
        ]
      }
    },
    "expr": [{"column": {"name": "id", "relation": {"relation": "alltypes_plain"}}}]
  }
}
```

2022-07-13 19:35 UTC, avantgardnerio approved these changes
After messing around a bit, I'm convinced this is just what we need. It does look like the `DefaultExtensionCodec` is not exposed in other packages? So maybe it makes sense to expose methods like `logical_plan_to_json()` for similar reasons as `logical_plan_to_bytes()` - making it easier to use from outside the `proto` crate...

2022-07-14 15:36 UTC, avantgardnerio requested changes
Please take a look at https://github.com/tustvold/arrow-datafusion/pull/64 before merging into Apache. I think those couple tweaks are important.

2022-07-14 21:10 UTC, avantgardnerio approved these changes

2022-07-15 17:48 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
>  tonic-build = { version = "0.7" }
```suggestion
pbjson-build = { version = "0.3", optional = true }
```

2022-07-15 17:48 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
> +pbjson-build = { version = "0.3", optional = true }
```suggestion
tonic-build = { version = "0.7" }
```

2022-07-16 15:14 UTC, tustvold commented on datafusion/proto/Cargo.toml
> +prost-build = { version = "0.7" }
There was actually no reason for this to depend on tonic-build, and not just prost-build. This is likely an orphan from when ballista was extracted

2022-07-17 15:11 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
>  datafusion-expr = { path = "../expr", version = "10.0.0" }
```suggestion
pbjson = { version = "0.3", optional = true }
pbjson-types = { version = "0.3", optional = true }
```

2022-07-17 15:12 UTC, avantgardnerio reviewed
Cargo fix sugestions

2022-07-17 15:12 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
>  datafusion-expr = { path = "../expr", version = "10.0.0" }
```suggestion
datafusion-expr = { path = "../expr", version = "10.0.0" }
pbjson = { version = "0.3", optional = true }
pbjson-types = { version = "0.3", optional = true }
```

2022-07-17 15:12 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
> +pbjson-types = { version = "0.3", optional = true }
```suggestion
```

2022-07-17 15:12 UTC, avantgardnerio commented on datafusion/proto/Cargo.toml
> +pbjson = { version = "0.3", optional = true }
```suggestion
```

2022-07-17 18:28 UTC, merged